## Numpy

파이썬에서 수학적 계산을 쉽게 할 수 있도록 가져오는 라이브러리 입니다.

ndarray: 행렬이라고 생각하면 된다.
nd는 n차원을 의미 (n dimensional)

주로 Tensorflow 나 pytorch, keras 등의 머신러닝 프레임워크에서 ndarray를 사용


In [6]:
# 모듈 불러오기
import numpy as np

In [ ]:
# 1차원 배열 생성
array = np.array(["A","B","C","D","E","F"])
array

In [2]:
list = ["A","B","C","D","E"]
list2=[1,2,3]
array=np.array(list2)
array

array([1, 2, 3])

In [4]:
print(array.shape) # 차원의 요소 개수
print(array.ndim) # 차원
print(array.dtype) # data type -> 공통적인 데이터 타입

(3,)
1
int64


In [8]:
# 2차원 배열 생성
array2=np.array([["A","B","C"],["D","E","F"]])
array2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

## 2.Numpy 형상 관련 함수

In [ ]:
# astype() - ndarray 타입변환
array5 = np.array([1,2,3,4,5])
print(array5.dtype)

In [ ]:
#* astype()
    #* ndarray의 타입을 변경 (int -> str, str -> int)

In [9]:
#각각
arr= np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
print(arr>6)
print(arr[arr>6])

[False False False False False False  True  True  True]
[7 8 9]


In [14]:
# 배열 연산
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])


add = np.add(arr1,arr2)
print(add)
print(arr1+arr2)

TypeError: 'builtin_function_or_method' object is not subscriptable