In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import seaborn as sns
from scipy import stats

# 최근접 이웃 실습

In [12]:
df= df=pd.read_csv("iris.csv")

In [13]:
df

sepal_length  sepal_width  petal_length  petal_width  class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [18]:
features = ['sepal_length','sepal_width','petal_length',"petal_width"]

In [20]:
X = df[features]
y = df["class"]

In [21]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [22]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int64

In [42]:
# 트레이닝/ 테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_tn,X_te,y_tn,y_te=train_test_split(X,y,random_state=0)#tn은 train te은 test

In [43]:
# 데이터 표준화 평균0 분산을 1로 만드는 과정
from sklearn.preprocessing import StandardScaler

In [44]:
std_scale = StandardScaler()

In [45]:
std_scale.fit(X_tn)# X_tn 를 평균0 분산1로 시킨다..

StandardScaler()

In [46]:
X_tn_std = std_scale.transform(X_tn)

In [48]:
X_tn_std 

array([[ 1.54399532e-02, -1.19254753e-01,  2.25126850e-01,
         3.55797625e-01],
       [-9.98450310e-02, -1.04039491e+00,  1.13559562e-01,
        -2.98410911e-02],
       [ 1.05300481e+00, -1.19254753e-01,  9.50314227e-01,
         1.12707506e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31530348e+00],
       [ 1.16828980e+00,  1.11030287e-01,  7.27179649e-01,
         1.38416753e+00],
       [-1.02212490e+00,  1.03217045e+00, -1.22524790e+00,
        -8.01118523e-01],
       [-5.60984968e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31530348e+00],
       [-1.02212490e+00, -2.42210516e+00, -1.65358660e-01,
        -2.86933568e-01],
       [ 7.07149859e-01, -1.19254753e-01,  9.50314227e-01,
         7.41436341e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.64126001e+00],
       [ 1.30724937e-01, -1.96153508e+00,  6.71396005e-01,
         3.55797625e-01],
       [ 9.37719827e-01, -1.27067995e+00,  1.11766516e+00,
      

In [47]:
X_te_std = std_scale.transform(X_te)# 변환해도 이데이터는 학습에 영향을 끼치지 않음

In [49]:
X_te_std

array([[-0.09984503, -0.57982483,  0.72717965,  1.51271377],
       [ 0.13072494, -1.96153508,  0.11355956, -0.28693357],
       [-0.44569998,  2.64416573, -1.33681519, -1.31530348],
       [ 1.62942973, -0.34953979,  1.39658338,  0.74143634],
       [-1.0221249 ,  0.80188541, -1.28103155, -1.31530348],
       [ 0.47657989,  0.57160037,  1.22923245,  1.64126001],
       [-1.0221249 ,  1.03217045, -1.39259884, -1.18675724],
       [ 0.93771983,  0.11103029,  0.50404507,  0.35579762],
       [ 1.05300481, -0.57982483,  0.55982872,  0.22725139],
       [ 0.24600992, -0.57982483,  0.11355956,  0.09870515],
       [ 0.24600992, -1.04039491,  1.00609787,  0.22725139],
       [ 0.59186487,  0.34131533,  0.39247778,  0.35579762],
       [ 0.24600992, -0.57982483,  0.50404507, -0.02984109],
       [ 0.70714986, -0.57982483,  0.44826143,  0.35579762],
       [ 0.24600992, -0.34953979,  0.50404507,  0.22725139],
       [-1.13740989,  1.26245549, -1.33681519, -1.44384972],
       [ 0.13072494, -0.

In [53]:
# 학습 [표준화된 문제집과 답지를 넣어준다.]
from sklearn.neighbors import KNeighborsClassifier
clf_knn= KNeighborsClassifier(n_neighbors=2)
clf_knn.fit(X_tn_std,y_tn)

KNeighborsClassifier(n_neighbors=2)

In [54]:
# 예측

In [58]:
knn_pred = clf_knn.predict(X_te_std)
print(knn_pred)

[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [59]:
# 정확도
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te,knn_pred)
print(accuracy)

0.9473684210526315


In [61]:
# 정밀도(precision)
from sklearn.metrics import precision_score
precision = precision_score(y_te, knn_pred, average='macro')
print(precision)

0.9421296296296297


In [62]:
# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, knn_pred, average='macro')
print(recall)

0.9421296296296297


In [63]:
# F1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, knn_pred, average='macro')
print(f1)

0.9421296296296297


In [64]:
# confusion matrix 확인 
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, knn_pred)
print(conf_matrix)

[[13  0  0]
 [ 0 15  1]
 [ 0  1  8]]


In [65]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_report = classification_report(y_te, knn_pred)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      0.94      0.94        16
           2       0.89      0.89      0.89         9

    accuracy                           0.95        38
   macro avg       0.94      0.94      0.94        38
weighted avg       0.95      0.95      0.95        38



# 선형 회귀 분석 실습