In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import seaborn as sns
from scipy import stats

# 최근접 이웃 실습

In [12]:
df=pd.read_csv("iris.csv")

In [13]:
df

sepal_length  sepal_width  petal_length  petal_width  class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [18]:
features = ['sepal_length','sepal_width','petal_length',"petal_width"]

In [20]:
X = df[features]
y = df["class"]

In [21]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [22]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int64

In [42]:
# 트레이닝/ 테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_tn,X_te,y_tn,y_te=train_test_split(X,y,random_state=0)#tn은 train te은 test

In [43]:
# 데이터 표준화 평균0 분산을 1로 만드는 과정
from sklearn.preprocessing import StandardScaler

In [44]:
std_scale = StandardScaler()

In [45]:
std_scale.fit(X_tn)# X_tn 를 평균0 분산1로 시킨다..

StandardScaler()

In [46]:
X_tn_std = std_scale.transform(X_tn)

In [48]:
X_tn_std 

array([[ 1.54399532e-02, -1.19254753e-01,  2.25126850e-01,
         3.55797625e-01],
       [-9.98450310e-02, -1.04039491e+00,  1.13559562e-01,
        -2.98410911e-02],
       [ 1.05300481e+00, -1.19254753e-01,  9.50314227e-01,
         1.12707506e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31530348e+00],
       [ 1.16828980e+00,  1.11030287e-01,  7.27179649e-01,
         1.38416753e+00],
       [-1.02212490e+00,  1.03217045e+00, -1.22524790e+00,
        -8.01118523e-01],
       [-5.60984968e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31530348e+00],
       [-1.02212490e+00, -2.42210516e+00, -1.65358660e-01,
        -2.86933568e-01],
       [ 7.07149859e-01, -1.19254753e-01,  9.50314227e-01,
         7.41436341e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.64126001e+00],
       [ 1.30724937e-01, -1.96153508e+00,  6.71396005e-01,
         3.55797625e-01],
       [ 9.37719827e-01, -1.27067995e+00,  1.11766516e+00,
      

In [47]:
X_te_std = std_scale.transform(X_te)# 변환해도 이데이터는 학습에 영향을 끼치지 않음

In [49]:
X_te_std

array([[-0.09984503, -0.57982483,  0.72717965,  1.51271377],
       [ 0.13072494, -1.96153508,  0.11355956, -0.28693357],
       [-0.44569998,  2.64416573, -1.33681519, -1.31530348],
       [ 1.62942973, -0.34953979,  1.39658338,  0.74143634],
       [-1.0221249 ,  0.80188541, -1.28103155, -1.31530348],
       [ 0.47657989,  0.57160037,  1.22923245,  1.64126001],
       [-1.0221249 ,  1.03217045, -1.39259884, -1.18675724],
       [ 0.93771983,  0.11103029,  0.50404507,  0.35579762],
       [ 1.05300481, -0.57982483,  0.55982872,  0.22725139],
       [ 0.24600992, -0.57982483,  0.11355956,  0.09870515],
       [ 0.24600992, -1.04039491,  1.00609787,  0.22725139],
       [ 0.59186487,  0.34131533,  0.39247778,  0.35579762],
       [ 0.24600992, -0.57982483,  0.50404507, -0.02984109],
       [ 0.70714986, -0.57982483,  0.44826143,  0.35579762],
       [ 0.24600992, -0.34953979,  0.50404507,  0.22725139],
       [-1.13740989,  1.26245549, -1.33681519, -1.44384972],
       [ 0.13072494, -0.

In [76]:
# 학습 [표준화된 문제집과 답지를 넣어준다.]
from sklearn.neighbors import KNeighborsClassifier
clf_knn= KNeighborsClassifier(n_neighbors=2)
clf_knn.fit(X_tn_std,y_tn)

KNeighborsClassifier(n_neighbors=2)

In [77]:
# 예측

In [78]:
knn_pred = clf_knn.predict(X_te_std)
print(knn_pred)

[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [79]:
# 정확도
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te,knn_pred)
print(accuracy)

0.9473684210526315


In [80]:
# 정밀도(precision)
from sklearn.metrics import precision_score
precision = precision_score(y_te, knn_pred, average='macro')
print(precision)

0.9421296296296297


In [81]:
# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, knn_pred, average='macro')
print(recall)

0.9421296296296297


In [82]:
# F1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, knn_pred, average='macro')
print(f1)

0.9421296296296297


In [83]:
# confusion matrix 확인 
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, knn_pred)
print(conf_matrix)

[[13  0  0]
 [ 0 15  1]
 [ 0  1  8]]


In [84]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_report = classification_report(y_te, knn_pred)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      0.94      0.94        16
           2       0.89      0.89      0.89         9

    accuracy                           0.95        38
   macro avg       0.94      0.94      0.94        38
weighted avg       0.95      0.95      0.95        38



# 선형 회귀 분석 실습

In [66]:
df=pd.read_csv("boston_house_prices.csv")

In [67]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [85]:
features = ["CRIM","ZN","CHAS","NOX","RM","AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT","MEDV"]

In [88]:
X = df[features]
X

CRIM    ZN  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0    0.00632  18.0     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1    0.02731   0.0     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2    0.02729   0.0     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3    0.03237   0.0     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4    0.06905   0.0     0  0.458  7.147  54.2  6.0622    3  222     18.7   
..       ...   ...   ...    ...    ...   ...     ...  ...  ...      ...   
501  0.06263   0.0     0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527   0.0     0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076   0.0     0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959   0.0     0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741   0.0     0  0.573  6.030  80.8  2.5050    1  273     21.0   

          B  LSTAT  MEDV  
0    396.90   4.98  24.0  
1    396.90   9.14  21.6  
2    392.83   4.03  34.7  
3    394.63   2.94  33.4  
4    396.90   5.33  36.2  
..      ...    ...   ...  
501  391.99   9.67  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9  

[506 rows x 13 columns]

In [89]:
y = df["MEDV"]
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [ ]:
# 데이터 표준화

In [90]:
from sklearn.preprocessing import StandardScaler

In [91]:
std_scale = StandardScaler()

In [92]:
std_scale.fit(X_tn)

StandardScaler()

In [93]:
X_tn_std = std_scale.transform(X_tn)

In [94]:
X_te_std = std_scale.transform(X_te)

In [ ]:
# 선형 회귀분석 학습

In [95]:
from sklearn.linear_model import LinearRegression

In [96]:
clf_lr = LinearRegression()

In [98]:
clf_lr.fit(X_tn_std,y_tn)

LinearRegression()

In [ ]:
# 선형 회귀 분석 모형 추정 계수 확인

In [100]:
print(clf_lr.coef_)

[-0.13297608 -0.01103311  0.4785993   0.44642447]


In [101]:
print(clf_lr.intercept_)

1.0357142857142858


In [112]:
# 릿지 회귀 분석(L2 제약식 적용)
from sklearn.linear_model import Ridge
clf_ridge = Ridge(alpha=1)
clf_ridge.fit(X_tn_std, y_tn)

Ridge(alpha=1)

In [113]:
# 라쏘 회귀분석(L1 제약식 적용)
from sklearn.linear_model import Lasso
clf_lasso = Lasso(alpha=0.01)
clf_lasso.fit(X_tn_std, y_tn)

Lasso(alpha=0.01)

In [114]:
# 엘라스틱넷
from sklearn.linear_model import ElasticNet
clf_elastic = ElasticNet(alpha=0.01, l1_ratio=0.01)
clf_elastic.fit(X_tn_std, y_tn)

ElasticNet(alpha=0.01, l1_ratio=0.01)

In [115]:
#예측
pred_lr = clf_lr.predict(X_te_std)
pred_ridge = clf_ridge.predict(X_te_std)
pred_lasso = clf_lasso.predict(X_te_std)
pred_elastic = clf_elastic.predict(X_te_std)

In [116]:
# 모형 평가-R제곱값
from sklearn.metrics import r2_score
print(r2_score(y_te, pred_lr))
print(r2_score(y_te, pred_ridge))
print(r2_score(y_te, pred_lasso))
print(r2_score(y_te, pred_elastic))

0.888612359879597
0.8912548621167725
0.8946166523543243
0.8914924323996021


In [117]:
# 모형 평가-MSE
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_te, pred_lr))
print(mean_squared_error(y_te, pred_ridge))
print(mean_squared_error(y_te, pred_lasso))
print(mean_squared_error(y_te, pred_elastic))

0.06325336904344218
0.06175277913036465
0.05984372927247513
0.06161787079800992


# 로지스틱 회귀 분석 실습

In [118]:
df=pd.read_csv("wine_data.csv")

In [119]:
df

Alcohol  Malic   Ash  Alcalinity  Magesium  Phenols  Flavanoids  \
0      14.23   1.71  2.43        15.6       127     2.80        3.06   
1      13.20   1.78  2.14        11.2       100     2.65        2.76   
2      13.16   2.36  2.67        18.6       101     2.80        3.24   
3      14.37   1.95  2.50        16.8       113     3.85        3.49   
4      13.24   2.59  2.87        21.0       118     2.80        2.69   
..       ...    ...   ...         ...       ...      ...         ...   
173    13.71   5.65  2.45        20.5        95     1.68        0.61   
174    13.40   3.91  2.48        23.0       102     1.80        0.75   
175    13.27   4.28  2.26        20.0       120     1.59        0.69   
176    13.17   2.59  2.37        20.0       120     1.65        0.68   
177    14.13   4.10  2.74        24.5        96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  class  
0             0.28             2.29   5.64  1.04      3.92     1065      0  
1             0.26             1.28   4.38  1.05      3.40     1050      0  
2             0.30             2.81   5.68  1.03      3.17     1185      0  
3             0.24             2.18   7.80  0.86      3.45     1480      0  
4             0.39             1.82   4.32  1.04      2.93      735      0  
..             ...              ...    ...   ...       ...      ...    ...  
173           0.52             1.06   7.70  0.64      1.74      740      2  
174           0.43             1.41   7.30  0.70      1.56      750      2  
175           0.43             1.35  10.20  0.59      1.56      835      2  
176           0.53             1.46   9.30  0.60      1.62      840      2  
177           0.56             1.35   9.20  0.61      1.60      560      2  

[178 rows x 14 columns]

In [120]:
features = ['Alcohol', 'Malic', 'Ash', 'Alcalinity', 'Magesium', 'Phenols', 'Flavanoids', 
            'Nonflavanoids', 'Proanthocyanins', 'Color','Hue', 'Dilution', 'Proline']

X = df[features]
y = df['class']

In [121]:
# 트레이닝/테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te=train_test_split(X,y,random_state=0)

In [122]:
#데이터 표준화
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std  = std_scale.transform(X_te)

In [123]:
# 로지스틱 회귀분석(L2 제약식 적용)
from sklearn.linear_model import LogisticRegression
clf_logi_l2 =  LogisticRegression(penalty='l2')
clf_logi_l2.fit(X_tn_std, y_tn)

LogisticRegression()

In [124]:
# 로지스틱 회귀분석 모형(L2 제약식 적용) 추정 계수
print(clf_logi_l2.coef_)
print(clf_logi_l2.intercept_)

[[ 0.69853977  0.25867826  0.39868195 -0.76815236 -0.00429211  0.18526119
   0.74915884 -0.12654939  0.10401364  0.17318889  0.13724279  0.68065574
   0.98907933]
 [-0.81533159 -0.47295284 -0.74058812  0.54948684 -0.08525548  0.01376966
   0.18741135  0.13017416  0.324744   -1.07084932  0.57591149  0.1276171
  -0.99183488]
 [ 0.11679181  0.21427458  0.34190617  0.21866552  0.08954759 -0.19903085
  -0.93657019 -0.00362477 -0.42875763  0.89766042 -0.71315428 -0.80827284
   0.00275554]]
[ 0.29606777  0.57687138 -0.87293914]


In [125]:
# 예측
pred_logistic = clf_logi_l2.predict(X_te_std)
print(pred_logistic)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [126]:
# 확률값으로 예측
pred_proba = clf_logi_l2.predict_proba(X_te_std)
print(pred_proba)

[[9.93360060e-01 4.92359807e-03 1.71634194e-03]
 [3.22076323e-04 2.77943948e-04 9.99399980e-01]
 [1.00535859e-02 9.89854907e-01 9.15071461e-05]
 [9.85578241e-01 1.15830075e-02 2.83875127e-03]
 [9.72825954e-02 8.94560998e-01 8.15640637e-03]
 [1.60778757e-01 8.37805552e-01 1.41569030e-03]
 [9.99185889e-01 2.82861666e-04 5.31249532e-04]
 [9.27747541e-04 6.79471537e-03 9.92277537e-01]
 [4.73077770e-03 9.94412333e-01 8.56889586e-04]
 [1.16783305e-03 9.96547896e-01 2.28427103e-03]
 [2.29360201e-02 1.70472078e-02 9.60016772e-01]
 [5.37945912e-04 2.05426668e-03 9.97407787e-01]
 [9.99868646e-01 4.18491948e-05 8.95049101e-05]
 [7.05474922e-02 9.29254258e-01 1.98249912e-04]
 [3.43785273e-03 1.00980993e-03 9.95552337e-01]
 [1.23126171e-04 9.99870752e-01 6.12188768e-06]
 [9.95131651e-01 3.26254700e-03 1.60580153e-03]
 [9.99969651e-01 5.43181185e-06 2.49174273e-05]
 [5.79978522e-03 7.64925188e-01 2.29275027e-01]
 [9.98986465e-01 9.25988748e-04 8.75463768e-05]
 [6.06195463e-02 9.39306550e-01 7.390404

In [127]:
# 정확도(accuracy)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_logistic)
print(accuracy)

1.0


In [128]:
# 정밀도(precision)
from sklearn.metrics import precision_score
precision = precision_score(y_te, pred_logistic, average='macro')
print(precision)

1.0


In [129]:
# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, pred_logistic, average='macro')
print(recall)

1.0


In [130]:
# confusion matrix 확인 
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_logistic)
print(conf_matrix)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]


In [131]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_report = classification_report(y_te, pred_logistic)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

