In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import seaborn as sns
from scipy import stats

In [2]:
df=pd.read_csv("wine_data.csv")

In [3]:
df

Alcohol  Malic   Ash  Alcalinity  Magesium  Phenols  Flavanoids  \
0      14.23   1.71  2.43        15.6       127     2.80        3.06   
1      13.20   1.78  2.14        11.2       100     2.65        2.76   
2      13.16   2.36  2.67        18.6       101     2.80        3.24   
3      14.37   1.95  2.50        16.8       113     3.85        3.49   
4      13.24   2.59  2.87        21.0       118     2.80        2.69   
..       ...    ...   ...         ...       ...      ...         ...   
173    13.71   5.65  2.45        20.5        95     1.68        0.61   
174    13.40   3.91  2.48        23.0       102     1.80        0.75   
175    13.27   4.28  2.26        20.0       120     1.59        0.69   
176    13.17   2.59  2.37        20.0       120     1.65        0.68   
177    14.13   4.10  2.74        24.5        96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  class  
0             0.28             2.29   5.64  1.04      3.92     1065      0  
1             0.26             1.28   4.38  1.05      3.40     1050      0  
2             0.30             2.81   5.68  1.03      3.17     1185      0  
3             0.24             2.18   7.80  0.86      3.45     1480      0  
4             0.39             1.82   4.32  1.04      2.93      735      0  
..             ...              ...    ...   ...       ...      ...    ...  
173           0.52             1.06   7.70  0.64      1.74      740      2  
174           0.43             1.41   7.30  0.70      1.56      750      2  
175           0.43             1.35  10.20  0.59      1.56      835      2  
176           0.53             1.46   9.30  0.60      1.62      840      2  
177           0.56             1.35   9.20  0.61      1.60      560      2  

[178 rows x 14 columns]

In [15]:
features = ['Alcohol', 'Malic', 'Ash', 'Alcalinity', 'Magesium', 'Phenols', 'Flavanoids', 
            'Nonflavanoids', 'Proanthocyanins', 'Color','Hue', 'Dilution', 'Proline']

X = df[features]
y = df['class']

In [16]:
# 트레이닝/테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te=train_test_split(X,y,random_state=0)

In [17]:
#데이터 표준화
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std  = std_scale.transform(X_te)

In [18]:
# 보팅 학습
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [22]:
clf1 = LogisticRegression(multi_class="multinomial",random_state=1)
clf2 = svm.SVC(kernel='linear') 
clf3 = GaussianNB()

clf_voting = VotingClassifier(
                estimators=[
                    ('lr', clf1), 
                    ('svm', clf2), 
                    ('gnb', clf3)
                ],
                voting='hard',
                weights=[1,1,1])
clf_voting.fit(X_tn_std, y_tn)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(multi_class='multinomial',
                                                 random_state=1)),
                             ('svm', SVC(kernel='linear')),
                             ('gnb', GaussianNB())],
                 weights=[1, 1, 1])

In [23]:
# 예측
pred_voting = clf_voting.predict(X_te_std)
print(pred_voting)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [24]:
# 정확도(accuracy)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_voting)
print(accuracy)

1.0


In [25]:
# 정밀도(precision)
from sklearn.metrics import precision_score
precision = precision_score(y_te, pred_voting, average='macro')
print(precision)

1.0


In [26]:
# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, pred_voting, average='macro')
print(recall)

1.0


In [28]:
# f1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, pred_voting, average='macro')
print(f1)

1.0


In [29]:
# confusion matrix 확인 
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_voting)
print(conf_matrix)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]


In [30]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_report = classification_report(y_te, pred_voting)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

