In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import seaborn as sns
from scipy import stats

# 내적 실습

In [3]:
df=pd.read_csv("WineQT.csv")


In [4]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [5]:
density = df['density']
pH = df["pH"]

In [6]:
#내적
res = np.inner(density,pH) 
print(res)

3771.9947731999996


In [7]:
#외적
res = np.outer(density,pH) 
print(res)

[[3.502278  3.19296   3.252828  ... 3.44241   3.512256  3.562146 ]
 [3.498768  3.18976   3.249568  ... 3.43896   3.508736  3.558576 ]
 [3.49947   3.1904    3.25022   ... 3.43965   3.50944   3.55929  ]
 ...
 [3.492099  3.18368   3.243374  ... 3.432405  3.502048  3.551793 ]
 [3.4928712 3.184384  3.2440912 ... 3.433164  3.5028224 3.5525784]
 [3.4940997 3.185504  3.2452322 ... 3.4343715 3.5040544 3.5538279]]


In [ ]:
# 고유값 실습

In [14]:
df=pd.read_csv("star_classification.csv")

In [15]:
df

Unnamed: 0        obj_ID       alpha      delta         u         g  \
0               0  1.237661e+18  135.689107  32.494632  23.87882  22.27530   
1               1  1.237665e+18  144.826101  31.274185  24.77759  22.83188   
2               2  1.237661e+18  142.188790  35.582444  25.26307  22.66389   
3               3  1.237663e+18  338.741038  -0.402828  22.13682  23.77656   
4               4  1.237680e+18  345.282593  21.183866  19.43718  17.58028   
...           ...           ...         ...        ...       ...       ...   
99995       99995  1.237679e+18   39.620709  -2.594074  22.16759  22.97586   
99996       99996  1.237679e+18   29.493819  19.798874  22.69118  22.38628   
99997       99997  1.237668e+18  224.587407  15.700707  21.16916  19.26997   
99998       99998  1.237661e+18  212.268621  46.660365  25.35039  21.63757   
99999       99999  1.237661e+18  196.896053  49.464643  22.62171  21.79745   

              r         i         z  run_ID  rerun_ID  cam_col  field_ID  \
0      20.39501  19.16573  18.79371    3606       301        2        79   
1      22.58444  21.16812  21.61427    4518       301        5       119   
2      20.60976  19.34857  18.94827    3606       301        2       120   
3      21.61162  20.50454  19.25010    4192       301        3       214   
4      16.49747  15.97711  15.54461    8102       301        3       137   
...         ...       ...       ...     ...       ...      ...       ...   
99995  21.90404  21.30548  20.73569    7778       301        2       581   
99996  20.45003  19.75759  19.41526    7917       301        1       289   
99997  18.20428  17.69034  17.35221    5314       301        4       308   
99998  19.91386  19.07254  18.62482    3650       301        4       131   
99999  20.60115  20.00959  19.28075    3650       301        4        60   

        spec_obj_ID  class  redshift  plate    MJD  fiber_ID  
0      6.543777e+18      0  0.634794   5812  56354       171  
1      1.176014e+19      0  0.779136  10445  58158       427  
2      5.152200e+18      0  0.644195   4576  55592       299  
3      1.030107e+19      0  0.932346   9149  58039       775  
4      6.891865e+18      0  0.116123   6121  56187       842  
...             ...    ...       ...    ...    ...       ...  
99995  1.055431e+19      0  0.000000   9374  57749       438  
99996  8.586351e+18      0  0.404895   7626  56934       866  
99997  3.112008e+18      0  0.143366   2764  54535        74  
99998  7.601080e+18      0  0.455040   6751  56368       470  
99999  8.343152e+18      0  0.542944   7410  57104       851  

[100000 rows x 19 columns]

In [16]:
df['class'].unique()

array([0, 1, 2])

In [17]:
sub_df = df[["u","g","r","i","z"]]
sub_df

u         g         r         i         z
0      23.87882  22.27530  20.39501  19.16573  18.79371
1      24.77759  22.83188  22.58444  21.16812  21.61427
2      25.26307  22.66389  20.60976  19.34857  18.94827
3      22.13682  23.77656  21.61162  20.50454  19.25010
4      19.43718  17.58028  16.49747  15.97711  15.54461
...         ...       ...       ...       ...       ...
99995  22.16759  22.97586  21.90404  21.30548  20.73569
99996  22.69118  22.38628  20.45003  19.75759  19.41526
99997  21.16916  19.26997  18.20428  17.69034  17.35221
99998  25.35039  21.63757  19.91386  19.07254  18.62482
99999  22.62171  21.79745  20.60115  20.00959  19.28075

[100000 rows x 5 columns]

In [18]:
# 고유값 분해
sub_df_t = np.transpose(sub_df)
sub_df_t

0         1         2         3         4         5         6      \
u  23.87882  24.77759  25.26307  22.13682  19.43718  23.48827  21.46973   
g  22.27530  22.83188  22.66389  23.77656  17.58028  23.33776  21.17624   
r  20.39501  22.58444  20.60976  21.61162  16.49747  21.32195  20.92829   
i  19.16573  21.16812  19.34857  20.50454  15.97711  20.25615  20.60826   
z  18.79371  21.61427  18.94827  19.25010  15.54461  19.54544  20.42573   

      7         8         9      ...     99990     99991     99992     99993  \
u  22.24979  24.40286  21.74669  ...  23.79655  26.22899  25.82234  23.13172   
g  22.02172  22.35669  20.03493  ...  22.41332  21.84820  24.02722  23.18506   
r  20.34126  20.61032  19.17553  ...  20.36012  20.47138  21.43137  21.52854   
i  19.48794  19.46490  18.81823  ...  19.33964  19.60049  20.13085  20.26975   
z  18.84999  18.95852  18.65422  ...  18.74413  18.94726  19.66464  20.11383   

      99994     99995     99996     99997     99998     99999  
u  20.96526  22.16759  22.69118  21.16916  25.35039  22.62171  
g  19.81625  22.97586  22.38628  19.26997  21.63757  21.79745  
r  19.34186  21.90404  20.45003  18.20428  19.91386  20.60115  
i  19.14711  21.30548  19.75759  17.69034  19.07254  20.00959  
z  19.05790  20.73569  19.41526  17.35221  18.62482  19.28075  

[5 rows x 100000 columns]

In [19]:
# 고유값 분해
cov_df =sub_df_t.dot(sub_df)
cov_df

u             g             r             i             z
u  1.492419e+08  1.459268e+08  4.350137e+07  4.220479e+07  1.416397e+08
g  1.459268e+08  1.429609e+08  4.070286e+07  3.949792e+07  1.389820e+08
r  4.350137e+07  4.070286e+07  3.893961e+07  3.780759e+07  3.699218e+07
i  4.220479e+07  3.949792e+07  3.780759e+07  3.673218e+07  3.594145e+07
z  1.416397e+08  1.389820e+08  3.699218e+07  3.594145e+07  1.355190e+08

In [20]:
e, v =np.linalg.eig(cov_df)

In [21]:
# 고유값
e

array([4.52407691e+08, 5.07357218e+07, 2.04743727e+05, 4.06186418e+04,
       4.77288840e+03])

In [23]:
# 고유백터
v

array([[-0.5733491 ,  0.0909501 , -0.67895384,  0.44905829,  0.01916291],
       [-0.56012813,  0.14008024, -0.03231131, -0.78254068, -0.23069477],
       [-0.18000134, -0.69174032, -0.04794331, -0.19084663,  0.67109898],
       [-0.17473995, -0.67196189,  0.16814737,  0.19588892, -0.67177911],
       [-0.54276399,  0.20510523,  0.71232406,  0.33343941,  0.21154596]])

In [25]:
# 특이값 분해
U,S,Vt = np.linalg.svd(cov_df)

In [26]:
#고유 백터
U

array([[-0.5733491 , -0.0909501 ,  0.67895384,  0.44905829, -0.01916291],
       [-0.56012813, -0.14008024,  0.03231131, -0.78254068,  0.23069477],
       [-0.18000134,  0.69174032,  0.04794331, -0.19084663, -0.67109898],
       [-0.17473995,  0.67196189, -0.16814737,  0.19588892,  0.67177911],
       [-0.54276399, -0.20510523, -0.71232406,  0.33343941, -0.21154596]])

In [27]:
#고유값
S

array([4.52407691e+08, 5.07357218e+07, 2.04743727e+05, 4.06186418e+04,
       4.77288840e+03])

In [29]:
# right singualr vector
Vt

array([[-0.5733491 , -0.56012813, -0.18000134, -0.17473995, -0.54276399],
       [-0.0909501 , -0.14008024,  0.69174032,  0.67196189, -0.20510523],
       [ 0.67895384,  0.03231131,  0.04794331, -0.16814737, -0.71232406],
       [ 0.44905829, -0.78254068, -0.19084663,  0.19588892,  0.33343941],
       [-0.01916291,  0.23069477, -0.67109898,  0.67177911, -0.21154596]])